In [1]:
# importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# making the moons dataset
from sklearn.datasets import make_moons
X,y = make_moons(n_samples=10000,noise=0.4)

In [7]:
X[:10]

array([[-1.0113172 ,  0.9184349 ],
       [-0.86941642,  0.78131359],
       [ 0.86019291, -0.04880088],
       [-0.8680585 ,  1.21986669],
       [ 0.91808445,  0.25252119],
       [-1.12579713,  0.03095333],
       [ 0.24113588, -0.07989638],
       [-0.21314057,  1.17805286],
       [ 0.7693152 , -0.32708694],
       [ 0.87955749, -0.38492562]])

In [8]:
y[:10]

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [9]:
# splitting dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
# Training the dataset on Decision Tree
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [12]:
# cross validation
from sklearn.model_selection import cross_val_score, GridSearchCV,StratifiedKFold
skf = StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
accuracy_score = cross_val_score(classifier,X_train[:1000],y_train[:1000],cv=skf,scoring='accuracy')
print(f'The accuracy score is {accuracy_score.mean()} with variation {accuracy_score.std()}')

The accuracy score is 0.778 with variation 0.03815756805667782


In [ ]:
# Grid Search to find the hyperparameter
param = {
    'criterion' : ['gini','entropy'],
    'max_leaf_nodes' : list(range(2,100)),
    'splitter' : ['best','random'],
    'max_depth': [2,3,4,5,6,7],
    'min_samples_leaf' : [2,3,4,5,6],
    'min_samples_split' : [2,3,4]
}
grid_search = GridSearchCV(classifier,param_grid=param,scoring='accuracy',cv=skf)
grid_search.fit(X_train,y_train)
print(f'The best accuracy score is {grid_search.best_score_}')
print(f'The best parameter is {grid_search.best_params_}')
best_model = grid_search.best_estimator_

The best accuracy score is 0.8566249999999999
The best parameter is {'criterion': 'gini', 'max_depth': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'min_samples_split': 2, 'splitter': 'best'}


In [32]:
y_pred = best_model.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(f'The accuracy score is {accuracy_score(y_test,y_pred)}')
confusion_matrix(y_test,y_pred)

The accuracy score is 0.8445


array([[886, 121],
       [190, 803]])